//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CgemoHivTests.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAnalysis
    {
        public PersonAnalysis()
        {
            this.ResponsesToDeclarants = new HashSet<ResponsesToDeclarant>();
        }
    
        public int PersonId { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportDateOfIssue { get; set; }
        public string Country { get; set; }
        public string CertNumber { get; set; }
        public System.DateTime CertDateOfIssue { get; set; }
        public System.DateTime AnalysisDate { get; set; }
        public bool AnalysisResult { get; set; }
    
        public virtual ICollection<ResponsesToDeclarant> ResponsesToDeclarants { get; set; }
    }
}
