//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CgemoHivTests.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsesToDeclarant
    {
        public int Id { get; set; }
        public string ResponseNumber { get; set; }
        public System.DateTime ResponseDate { get; set; }
        public string RequestNumber { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.Guid UserId { get; set; }
        public int DeclarantId { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual Declarant Declarant { get; set; }
        public virtual PersonAnalysis Person { get; set; }
        public virtual User User { get; set; }
    }
}
