//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CgemoHivTests.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateLog
    {
        public int Id { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public System.DateTime DateFirst { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int TotalRecords { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
