//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CgemoHivTests.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ResponsesToDeclarants = new HashSet<ResponsesToDeclarant>();
            this.UpdateLogs = new HashSet<UpdateLog>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public string Email { get; set; }
        public string LoweredEmail { get; set; }
        public string Password { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
    
        public virtual ICollection<ResponsesToDeclarant> ResponsesToDeclarants { get; set; }
        public virtual ICollection<UpdateLog> UpdateLogs { get; set; }
    }
}
